### ISSUE TITLE
Version Lock `requirements.txt`

### ISSUE THREAD

**Issue by siddk** [bigscience-workshop/Megatron-DeepSpeed#145]
Might be good to either specify versions, or ideally, switch to a conda environment for this repo. Critically, the base requirements for Megatron-DeepSpeed in `requirements.txt` just require "torch" whereas you actually need torch > 1.7.0, notably with CUDA 11.1 or higher for this repo to actually work!

**Comment by jaketae** [comment]
I remember discussing this with @stas00 in #46 some time ago. Linking the thread in case it becomes relevant!

**Comment by siddk** [comment]
My bad on CUDA-10 - I need 11.1 to build the triton dependency for DeepSpeed (I was using the current instructions in the README, which should probably be updated).

1.7 is the first PyTorch version supporting Ampere cards + TF32; for JZ, since we're on V100s probably not an issue, but for newer cards (3XXXs, A100s) this is pretty nice for performance. 

Also with 1.9, better layernorm kernels, faster ops across the board, and the profiler! The profiler is amazing!

**Comment by stas00** [comment]
> My bad on CUDA-10 - I need 11.1 to build the triton dependency for DeepSpeed (I was using the current instructions in the README, which should probably be updated).
>
> 1.7 is the first PyTorch version supporting Ampere cards + TF32; for JZ, since we're on V100s probably not an issue, but for newer cards (3XXXs, A100s) this is pretty nice for performance.
 
Both of these aren't project requirements but user's - each user knows what components they need to work on their card. We shouldn't set project requirements to the highest requirements of the user using the latest hardware.

e.g. I had to use pytorch-nightly for all of winter and some spring before Amphere was supported, but that was my need and not of others.

--------------------

> But yeah - I think CUDA >10.1 is fine if we're not trying to build the more complex DS kernels.

I don't think this is so either. Deepspeed currently supports pt=1.2.

**Comment by siddk** [comment]
Got it; so performance is the only real issue then? Do we want to lock versions to min-runnable, or do we want to actually gate on performance? 

I could imagine confusion down the line that the same models that fit on newer cards due to some DS/Megatron enhancements don’t necessarily work (or work reliably) on older cards because of an “effective” torch/ds/CUDA version.

Generally my solution for reproducibility in the future (in case there are bugs/robustness to future features) is to freeze requirements based on what we’re running on a day-to-day.

@stas00 how do you feel about keeping a “min-requirements.txt” instead and then a “locked” requirements.txt so we can have some consistency? Especially if we want to benchmark/reproduce results later?

**Comment by stas00** [comment]
> Got it; so performance is the only real issue then? Do we want to lock versions to min-runnable, or do we want to actually gate on performance?

Nope. Performance is also a prerogative of a user. One should always avoid setting any hardcoded requirements because there is always a chance of conflict with other dependent package requirements.

In the case of Meg-DS, Meg has no torch requirements, DS's is 1.2, so it's safe to not set any minimal requirements.

Should we discover that the code doesn't run due to a certain problem or a bug, we will then set the minimal requirement for that particular package.
 
> I could imagine confusion down the line that the same models that fit on newer cards due to some DS/Megatron enhancements don’t necessarily work (or work reliably) on older cards because of an “effective” torch/ds/CUDA version.

The main back-compat issue for models is modern models trained in bf16, which don't do well under fp16.

The rest should work almost identically under older cards.

> Generally my solution for reproducibility in the future (in case there are bugs/robustness to future features) is to freeze requirements based on what we’re running on a day-to-day.

For your own needs or for needs of a training, for sure. But not for different users and groups that have different requirements.

> @stas00 how do you feel about keeping a “min-requirements.txt” instead and then a “locked” requirements.txt so we can have some consistency? Especially if we want to benchmark/reproduce results later?

I think this is a waste of maintainers' time and a source of confusion to users.

I suggest for to create your own bash alias where you set the desired requirements. This is what I do.

When one does a benchmark one either encodes the hardcore requirements in the benchmark code or one adds a documentation (or both).

To reproduce issues, versions is often insufficient, you need SHA numbers for each project, since quite a few of the ones we use are master branches. (or `main` for the modern politically correct populaces).
